<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'dc0ea4af75c148bb041f3d6e96b7c578',
  'DATABASE_URL' => 'mysql://milloncth:milloncth@127.0.0.1:3306/milloncth?serverVersion=mariadb-10.3.25',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '992f0e9aa473848386cb7dbb2e9d7436ef196571a422a3fd8a76a46d93012b6c',
  'LOCK_DSN' => 'flock',
);
